"""Drop some of the Bookings table nullable constraints

Revision ID: a2f1508afd07
Revises: 7eb681053564
Create Date: 2024-10-31 14:52:19.280064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f1508afd07'
down_revision: Union[str, None] = '7eb681053564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'room_id',
               existing_type=sa.Integer(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.Integer(),
               nullable=True)
    op.alter_column('bookings', 'total_cost',
                    existing_type=sa.Integer(),
                    nullable=True)
    op.alter_column('bookings', 'total_days',
                    existing_type=sa.Integer(),
                    nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'total_cost',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('bookings', 'total_days',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
